spring:
    main:
        bannerMode: "off"

logging:
    level:
        ROOT: INFO
        com.netflix: WARN
        com.netflix.config: ERROR
        com.netflix.discovery: ERROR
        org.apache.catalina: WARN
        org.springframework: WARN
        org.springframework.boot.web.embedded: INFO

server:
    port: 10080

---
spring:
    profiles: https

server:
    ssl:
        enabled: true
        protocol: TLS
        enabledProtocols: TLSv1.2
        ciphers: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA,TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_128_CBC_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_CBC_SHA384

---
spring:
    profiles: debug


logging:
    level:
        ROOT: INFO
        org.springframework: INFO
        org.apache.catalina: INFO
        com.netflix: INFO

---
spring:
    profiles: diag

management:
    endpoints:
        web:
            exposure:
                include: "*"
