version: 2.1
orbs:
  codecov: codecov/codecov@1.1.1
jobs:
  build_all:
    docker:
      - image: circleci/openjdk:8-jdk-node
        environment:
          # kotlin.incremental=false and kotlin.compiler.execution.strategy=in-process are required due to an issue with the Kotlin compiler in
          # memory constrained environments: https://youtrack.jetbrains.com/issue/KT-15562
          _JAVA_OPTIONS: "-Xmx3g"
          GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.workers.max=2 -Xmx1536m -XX:+HeapDumpOnOutOfMemoryError -Dorg.gradle.caching=true -Dorg.gradle.configureondemand=true -Dkotlin.compiler.execution.strategy=in-process -Dkotlin.incremental=false
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache: &keys
          keys:
            - v3-zowe-sdk-{{ .Branch }}
            - v3-zowe-sdk-master
      - run: &build_jarpatcher
          name: Building JAR Patcher using Gradle
          command: ./gradlew :jarpatcher:build
      - run: &build_devtool
          name: Building zowe-api-dev Tool
          command: |
            cd zowe-api-dev
            npm install
            npm pack
            mkdir -p ../build/
            cp -v zowedev-zowe-api-dev-*.tgz ../build/zowedev-zowe-api-dev.tgz
      - store_artifacts:
          path: build/zowedev-zowe-api-dev.tgz
          destination: zowedev-zowe-api-dev.tgz
      - run: &zosbuild
          name: Building Native z/OS Code
          command: |
            echo "==="
            pwd
            npm uninstall @zowedev/zowe-api-dev
            npm install
            sudo npm install -g ./build/zowedev-zowe-api-dev.tgz
            source .circleci/marist.env
            npm run zosbuild
      - run: &build
          name: Building Java Code using Gradle
          command: |
            ./gradlew build
            scripts/so-test.sh
      - codecov/upload
      - persist_to_workspace:
          root: .
          paths:
            - build/*
            - zowe-rest-api-commons-spring/build/*
            - zowe-rest-api-sample-kotlin-spring/build/*
            - zowe-rest-api-sample-spring/build/*
            - jarpatcher/build/*
      - run: &sample
          name: Building Standalone Sample
          command: |
            scripts/build-sample.sh
      - store_artifacts:
          path: build/zowe-rest-api-sample-spring.jar
          destination: zowe-rest-api-sample-spring.jar
      - store_artifacts:
          path: zowe-rest-api-sample-spring/build/pom.xml
          destination: zowe-rest-api-sample-spring/pom.xml
      - store_artifacts:
          path: zowe-rest-api-commons-spring/build/pom.xml
          destination: zowe-rest-api-commons-spring/pom.xml
      - run: &integration_tests_sample
          name: Running Integration Tests of the Sample in the Build Container
          command: |
            scripts/run-integration-tests.sh
      - run: &integration_tests_sample_zos
          name: Running Integration Tests of the Sample on z/OS
          command: |
            source .circleci/marist.env
            npm run zos-integration-tests
      - run: &integration_tests_kotlin_sample
          name: Running Integration Tests of the Kotlin Sample in the Build Container
          command: |
            scripts/run-integration-tests-kotlin.sh
      - run: &integration_tests_kotlin_sample_zos
          name: Running Integration Tests of the Kotlin Sample on z/OS
          command: |
            source .circleci/marist.env
            npm run zos-kotlin-integration-tests
      - store_test_results:
          path: zowe-rest-api-commons-spring/build/test-results
      - store_test_results:
          path: zowe-rest-api-sample-spring/build/test-results
      - run: &zos_cleanup
          name: Cleanup on z/OS
          when: always
          command: |
            source .circleci/marist.env
            npm run zos-cleanup
            scripts/package-sample.sh
      - store_artifacts:
          path: ~/code/build/zowe-rest-api-sample-spring.zip
          destination: zowe-rest-api-sample-spring.zip
      - save_cache:
          paths:
            - ~/.gradle
            - ~/code/.gradle
            - ~/code/node_modules
            - ~/code/zowe-api-dev/node_modules
            - ~/code/zowe-rest-api-sample-spring/.gradle
            - ~/code/gradle/wrapper/gradle-wrapper.jar
          key: v3-zowe-sdk-{{ .Branch }}-{{ epoch }}
  sonar:
    docker:
      - image: 'circleci/openjdk:11-jdk'
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run: &sonar
          name: Sonar
          command: |
            ./gradlew --info sonarqube -Psonar.host.url=https://sonarcloud.io -Dsonar.login=$SONAR_AUTH_TOKEN -x test -x compileTestJava
  coverity_scan:
    docker:
      - image: plavjanik/coverity-oss
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Coverity Capture Build and Start Analysis
          command: scripts/coverity-scan.sh
  publish_all:
    docker:
      - image: circleci/openjdk:8-jdk-node
    working_directory: ~/code
    steps:
      - checkout
      - restore_cache: *keys
      - run: *build_jarpatcher
      - run: *build_devtool
      - run: *zosbuild
      - run: *build
      - codecov/upload
      - run: *sonar
      - run: *sample
      - run: *integration_tests_sample
      - run: *integration_tests_sample_zos
      - run: *integration_tests_kotlin_sample
      - run: *integration_tests_kotlin_sample_zos
      - run: *zos_cleanup
      - run:
          name: Publishing zowe-api-dev Tool to npmjs.com
          command: |
            ./gradlew :jarpatcher:build
            cd zowe-api-dev
            npm install
            npm version `git describe --tags --abbrev=0 | cut -c2-`
            npm pack
            echo "//registry.npmjs.org/:_authToken=$NPMJS_TOKEN" > ~/.npmrc
            npm publish --access public
      - run:
          name: Upload Java Libraries to Bintray using Gradle
          command: |
            ./gradlew bintrayUpload
      - run:
          name: Upload Sample Source Code to GitHub Release
          command: |
            scripts/package-sample.sh
            scripts/publish-sample.sh

workflows:
  version: 2
  untagged_build:
    jobs:
      - build_all:
          filters:
            tags:
              ignore: /.*/
      - sonar:
          filters:
            tags:
              ignore: /.*/
          requires:
            - build_all
      - coverity_scan:
          filters:
            branches:
              only:
                - master
  tagged_build:
    jobs:
      - publish_all:
          filters:
            tags:
              only: /v.*/
            branches:
              ignore: /.*/
